//
//  Tokens.swift
//  Kadence
//
//  GENERATED FILE — DO NOT EDIT.
//
//  Generated by Scripts/generate-tokens.swift from design/tokens.json
//  Source fingerprint: fnv1a64:399e86a29e0518c6 (30290 bytes)
//
//  Every value below comes from design/tokens.json. To change one, edit the
//  JSON and re-run:
//
//      swift Scripts/generate-tokens.swift
//
//  Hand edits are overwritten on the next run and fail
//  `swift Scripts/generate-tokens.swift --check`.
//

import SwiftUI

#if canImport(AppKit)
import AppKit
#endif

enum Tokens {
    enum Color {
        enum Interactive {
            static var accent: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 10, green: 108, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 76, green: 155, blue: 255, alpha: 255)) }  // light #0A6CFF / dark #4C9BFF
            static let accentSystemName: Swift.String = "controlAccentColor"
            static var focusRing: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 10, green: 108, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 76, green: 155, blue: 255, alpha: 255)) }  // light #0A6CFF / dark #4C9BFF
            static var focusRingOnAccent: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 12, green: 12, blue: 13, alpha: 255)) }  // light #FFFFFF / dark #0C0C0D
            static let focusRingSystemName: Swift.String = "keyboardFocusIndicatorColor"
            static var hoverOverlay: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 15), dark: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 20)) }  // light #0000000F / dark #FFFFFF14
            static var pressedOverlay: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 23), dark: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 31)) }  // light #00000017 / dark #FFFFFF1F
            static var selectedCardFill: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 227, green: 237, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 31, green: 51, blue: 82, alpha: 255)) }  // light #E3EDFF / dark #1F3352
            static var selectedRowFill: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 10, green: 108, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 76, green: 155, blue: 255, alpha: 255)) }  // light #0A6CFF / dark #4C9BFF
            static let selectedRowFillSystemName: Swift.String = "selectedContentBackgroundColor"
        }

        enum Semantic {
            static var alert: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 177, green: 52, blue: 74, alpha: 255), dark: TokenSupport.RGBA(red: 255, green: 149, blue: 158, alpha: 255)) }  // light #B1344A / dark #FF959E
            static var alertOnFill: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 12, green: 12, blue: 13, alpha: 255)) }  // light #FFFFFF / dark #0C0C0D
            static var now: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 217, green: 59, blue: 48, alpha: 255), dark: TokenSupport.RGBA(red: 255, green: 107, blue: 94, alpha: 255)) }  // light #D93B30 / dark #FF6B5E
        }

        enum Separator {
            static var dayDivider: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 213, green: 213, blue: 217, alpha: 255), dark: TokenSupport.RGBA(red: 59, green: 59, blue: 64, alpha: 255)) }  // light #D5D5D9 / dark #3B3B40
            static var halfHour: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 240, green: 240, blue: 242, alpha: 255), dark: TokenSupport.RGBA(red: 38, green: 38, blue: 41, alpha: 255)) }  // light #F0F0F2 / dark #262629
            static var hour: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 227, green: 227, blue: 229, alpha: 255), dark: TokenSupport.RGBA(red: 49, green: 49, blue: 53, alpha: 255)) }  // light #E3E3E5 / dark #313135
            static var region: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 213, green: 213, blue: 217, alpha: 255), dark: TokenSupport.RGBA(red: 59, green: 59, blue: 64, alpha: 255)) }  // light #D5D5D9 / dark #3B3B40
            static var strong: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 138, green: 143, blue: 151, alpha: 255), dark: TokenSupport.RGBA(red: 126, green: 131, blue: 140, alpha: 255)) }  // light #8A8F97 / dark #7E838C
        }

        enum Source {
            enum Amber {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 117, green: 97, blue: 0, alpha: 255), dark: TokenSupport.RGBA(red: 210, green: 176, blue: 0, alpha: 255)) }  // light #756100 / dark #D2B000
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 133, green: 111, blue: 0, alpha: 255), dark: TokenSupport.RGBA(red: 195, green: 164, blue: 0, alpha: 255)) }  // light #856F00 / dark #C3A400
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 119, green: 98, blue: 0, alpha: 255), dark: TokenSupport.RGBA(red: 188, green: 158, blue: 0, alpha: 255)) }  // light #776200 / dark #BC9E00
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 237, green: 234, blue: 222, alpha: 255), dark: TokenSupport.RGBA(red: 55, green: 50, blue: 25, alpha: 255)) }  // light #EDEADE / dark #373219
            }

            enum Blue {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 30, green: 96, blue: 189, alpha: 255), dark: TokenSupport.RGBA(red: 129, green: 180, blue: 255, alpha: 255)) }  // light #1E60BD / dark #81B4FF
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 46, green: 112, blue: 205, alpha: 255), dark: TokenSupport.RGBA(red: 107, green: 166, blue: 255, alpha: 255)) }  // light #2E70CD / dark #6BA6FF
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 31, green: 97, blue: 190, alpha: 255), dark: TokenSupport.RGBA(red: 98, green: 162, blue: 255, alpha: 255)) }  // light #1F61BE / dark #62A2FF
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 226, green: 234, blue: 246, alpha: 255), dark: TokenSupport.RGBA(red: 43, green: 51, blue: 64, alpha: 255)) }  // light #E2EAF6 / dark #2B3340
            }

            enum Graphite {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 95, green: 99, blue: 106, alpha: 255), dark: TokenSupport.RGBA(red: 174, green: 179, blue: 186, alpha: 255)) }  // light #5F636A / dark #AEB3BA
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 109, green: 113, blue: 120, alpha: 255), dark: TokenSupport.RGBA(red: 161, green: 166, blue: 174, alpha: 255)) }  // light #6D7178 / dark #A1A6AE
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 97, green: 101, blue: 108, alpha: 255), dark: TokenSupport.RGBA(red: 157, green: 161, blue: 169, alpha: 255)) }  // light #61656C / dark #9DA1A9
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 234, green: 235, blue: 236, alpha: 255), dark: TokenSupport.RGBA(red: 50, green: 51, blue: 53, alpha: 255)) }  // light #EAEBEC / dark #323335
            }

            enum Green {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 114, blue: 27, alpha: 255), dark: TokenSupport.RGBA(red: 100, green: 199, blue: 107, alpha: 255)) }  // light #00721B / dark #64C76B
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 18, green: 130, blue: 38, alpha: 255), dark: TokenSupport.RGBA(red: 87, green: 186, blue: 94, alpha: 255)) }  // light #128226 / dark #57BA5E
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 116, blue: 28, alpha: 255), dark: TokenSupport.RGBA(red: 81, green: 180, blue: 88, alpha: 255)) }  // light #00741C / dark #51B458
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 222, green: 237, blue: 225, alpha: 255), dark: TokenSupport.RGBA(red: 39, green: 54, blue: 42, alpha: 255)) }  // light #DEEDE1 / dark #27362A
            }

            enum Orange {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 161, green: 74, blue: 0, alpha: 255), dark: TokenSupport.RGBA(red: 255, green: 154, blue: 94, alpha: 255)) }  // light #A14A00 / dark #FF9A5E
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 183, green: 84, blue: 0, alpha: 255), dark: TokenSupport.RGBA(red: 249, green: 136, blue: 65, alpha: 255)) }  // light #B75400 / dark #F98841
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 162, green: 74, blue: 0, alpha: 255), dark: TokenSupport.RGBA(red: 242, green: 131, blue: 59, alpha: 255)) }  // light #A24A00 / dark #F2833B
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 243, green: 231, blue: 222, alpha: 255), dark: TokenSupport.RGBA(red: 62, green: 47, blue: 40, alpha: 255)) }  // light #F3E7DE / dark #3E2F28
            }

            enum Pink {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 164, green: 57, blue: 125, alpha: 255), dark: TokenSupport.RGBA(red: 255, green: 140, blue: 208, alpha: 255)) }  // light #A4397D / dark #FF8CD0
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 181, green: 72, blue: 140, alpha: 255), dark: TokenSupport.RGBA(red: 241, green: 127, blue: 195, alpha: 255)) }  // light #B5488C / dark #F17FC3
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 165, green: 58, blue: 126, alpha: 255), dark: TokenSupport.RGBA(red: 235, green: 121, blue: 189, alpha: 255)) }  // light #A53A7E / dark #EB79BD
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 243, green: 229, blue: 238, alpha: 255), dark: TokenSupport.RGBA(red: 62, green: 45, blue: 57, alpha: 255)) }  // light #F3E5EE / dark #3E2D39
            }

            enum Purple {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 119, green: 75, blue: 180, alpha: 255), dark: TokenSupport.RGBA(red: 196, green: 163, blue: 255, alpha: 255)) }  // light #774BB4 / dark #C4A3FF
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 133, green: 91, blue: 196, alpha: 255), dark: TokenSupport.RGBA(red: 186, green: 145, blue: 255, alpha: 255)) }  // light #855BC4 / dark #BA91FF
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 121, green: 78, blue: 182, alpha: 255), dark: TokenSupport.RGBA(red: 182, green: 140, blue: 250, alpha: 255)) }  // light #794EB6 / dark #B68CFA
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 237, green: 232, blue: 245, alpha: 255), dark: TokenSupport.RGBA(red: 53, green: 48, blue: 64, alpha: 255)) }  // light #EDE8F5 / dark #353040
            }

            enum Teal {
                static var rail: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 109, blue: 111, alpha: 255), dark: TokenSupport.RGBA(red: 0, green: 199, blue: 200, alpha: 255)) }  // light #006D6F / dark #00C7C8
                static var solid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 126, blue: 127, alpha: 255), dark: TokenSupport.RGBA(red: 0, green: 184, blue: 186, alpha: 255)) }  // light #007E7F / dark #00B8BA
                static var text: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 112, blue: 113, alpha: 255), dark: TokenSupport.RGBA(red: 0, green: 178, blue: 179, alpha: 255)) }  // light #007071 / dark #00B2B3
                static var tint: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 222, green: 236, blue: 236, alpha: 255), dark: TokenSupport.RGBA(red: 24, green: 54, blue: 56, alpha: 255)) }  // light #DEECEC / dark #183638
            }
        }

        enum SourcePalette {
            static let adjacencyWarning: Swift.String = "orange and amber are the closest pair (hue 50 / 95). Do not auto-assign them to the two highest-volume sources; assignment order above already separates them."
            static let assignmentRule: Swift.String = "Assign in listed order as sources are added. graphite is the fallback for any source with no colour and for origin == .manual."
            static let order: [Swift.String] = ["blue", "teal", "green", "amber", "orange", "pink", "purple", "graphite"]
            static let reserved: Swift.String = "Red is NOT in the source palette. It is reserved for semantic.now and semantic.alert so that red never means 'a source' anywhere in the app."
        }

        enum Surface {
            static var allDayRow: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 252, green: 252, blue: 253, alpha: 255), dark: TokenSupport.RGBA(red: 31, green: 31, blue: 34, alpha: 255)) }  // light #FCFCFD / dark #1F1F22
            static var canvas: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 28, green: 28, blue: 30, alpha: 255)) }  // light #FFFFFF / dark #1C1C1E
            static var canvasAlt: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 247, green: 247, blue: 248, alpha: 255), dark: TokenSupport.RGBA(red: 33, green: 33, blue: 36, alpha: 255)) }  // light #F7F7F8 / dark #212124
            static var canvasSunken: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 241, green: 241, blue: 243, alpha: 255), dark: TokenSupport.RGBA(red: 22, green: 22, blue: 24, alpha: 255)) }  // light #F1F1F3 / dark #161618
            static var inspector: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 247, green: 247, blue: 248, alpha: 255), dark: TokenSupport.RGBA(red: 33, green: 33, blue: 36, alpha: 255)) }  // light #F7F7F8 / dark #212124
            static var popover: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 42, green: 42, blue: 46, alpha: 255)) }  // light #FFFFFF / dark #2A2A2E
            static let popoverMaterial: Swift.String = "popover"
            static var sidebar: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 242, green: 242, blue: 244, alpha: 255), dark: TokenSupport.RGBA(red: 35, green: 35, blue: 38, alpha: 255)) }  // light #F2F2F4 / dark #232326
            static let sidebarMaterial: Swift.String = "sidebar"
            static var toolbar: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 242, green: 242, blue: 244, alpha: 255), dark: TokenSupport.RGBA(red: 35, green: 35, blue: 38, alpha: 255)) }  // light #F2F2F4 / dark #232326
            static let toolbarMaterial: Swift.String = "headerView"
            static var travelBand: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 241, green: 241, blue: 243, alpha: 255), dark: TokenSupport.RGBA(red: 40, green: 40, blue: 44, alpha: 255)) }  // light #F1F1F3 / dark #28282C
        }

        enum Text {
            static var onSolid: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 255), dark: TokenSupport.RGBA(red: 12, green: 12, blue: 13, alpha: 255)) }  // light #FFFFFF / dark #0C0C0D
            static var primary: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 26, green: 26, blue: 28, alpha: 255), dark: TokenSupport.RGBA(red: 242, green: 242, blue: 244, alpha: 255)) }  // light #1A1A1C / dark #F2F2F4
            static var secondary: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 91, green: 95, blue: 102, alpha: 255), dark: TokenSupport.RGBA(red: 168, green: 173, blue: 181, alpha: 255)) }  // light #5B5F66 / dark #A8ADB5
            static var tertiary: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 138, green: 143, blue: 151, alpha: 255), dark: TokenSupport.RGBA(red: 126, green: 131, blue: 140, alpha: 255)) }  // light #8A8F97 / dark #7E838C
        }

        enum Window {
            static var label: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 138, green: 143, blue: 151, alpha: 255), dark: TokenSupport.RGBA(red: 126, green: 131, blue: 140, alpha: 255)) }  // light #8A8F97 / dark #7E838C
            static var lowEnergyFill: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 0), dark: TokenSupport.RGBA(red: 28, green: 28, blue: 30, alpha: 0)) }  // light #FFFFFF00 / dark #1C1C1E00
            static var lowEnergyHatch: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 228, green: 228, blue: 232, alpha: 255), dark: TokenSupport.RGBA(red: 47, green: 47, blue: 52, alpha: 255)) }  // light #E4E4E8 / dark #2F2F34
            static var peakFocusEdge: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 129, green: 145, blue: 165, alpha: 255), dark: TokenSupport.RGBA(red: 92, green: 109, blue: 127, alpha: 255)) }  // light #8191A5 / dark #5C6D7F
            static var peakFocusFill: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 255, green: 255, blue: 255, alpha: 0), dark: TokenSupport.RGBA(red: 28, green: 28, blue: 30, alpha: 0)) }  // light #FFFFFF00 / dark #1C1C1E00
            static var protectedEdge: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 222, green: 222, blue: 225, alpha: 255), dark: TokenSupport.RGBA(red: 58, green: 58, blue: 63, alpha: 255)) }  // light #DEDEE1 / dark #3A3A3F
            static var protectedEdgeHC: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 138, green: 143, blue: 151, alpha: 255), dark: TokenSupport.RGBA(red: 126, green: 131, blue: 140, alpha: 255)) }  // light #8A8F97 / dark #7E838C
            static var protectedFill: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 242, green: 242, blue: 243, alpha: 255), dark: TokenSupport.RGBA(red: 36, green: 36, blue: 39, alpha: 255)) }  // light #F2F2F3 / dark #242427
        }
    }

    enum Elevation {
        enum Level0 {
            static let blur: CoreGraphics.CGFloat = 0
            static var color: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 0), dark: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 0)) }  // light #00000000 / dark #00000000
            static let hasShadow: Swift.Bool = false
            static let y: CoreGraphics.CGFloat = 0
        }

        enum Level1 {
            static let blur: CoreGraphics.CGFloat = 3
            static var color: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 38), dark: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 89)) }  // light #00000026 / dark #00000059
            static let hasShadow: Swift.Bool = true
            static let y: CoreGraphics.CGFloat = 1
        }

        enum Level2 {
            static let blur: CoreGraphics.CGFloat = 12
            static var color: SwiftUI.Color { TokenSupport.color(light: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 51), dark: TokenSupport.RGBA(red: 0, green: 0, blue: 0, alpha: 107)) }  // light #00000033 / dark #0000006B
            static let hasShadow: Swift.Bool = true
            static let y: CoreGraphics.CGFloat = 4
        }
    }

    enum Motion {
        enum BlockMove {
            static let reduceMotion: Swift.String = "no movement; 0.12 cross-fade between slots plus a 0.60 destination outline hold"
            static let settle: CoreGraphics.CGFloat = 0.12

            enum Spring {
                static let dampingFraction: CoreGraphics.CGFloat = 0.86
                static let response: CoreGraphics.CGFloat = 0.26
            }
        }

        enum Hover {
            static let curve: Swift.String = "easeOut"
            static let duration: CoreGraphics.CGFloat = 0.09
            static let reduceMotion: Swift.String = "unchanged"
        }

        enum NowLineTick {
            static let curve: Swift.String = "linear"
            static let duration: CoreGraphics.CGFloat = 0.2
            static let interval: CoreGraphics.CGFloat = 60
            static let reduceMotion: Swift.String = "instant reposition"
        }

        enum OutlineHold {
            static let curve: Swift.String = "easeInOut"
            static let duration: CoreGraphics.CGFloat = 0.6
            static let reduceMotion: Swift.String = "unchanged"
        }

        enum Paging {
            static let curve: Swift.String = "easeOut"
            static let duration: CoreGraphics.CGFloat = 0.14
            static let reduceMotion: Swift.String = "instant swap, no slide"
        }

        enum PreviewRevert {
            static let curve: Swift.String = "easeOut"
            static let duration: CoreGraphics.CGFloat = 0.12
            static let reduceMotion: Swift.String = "unchanged — this is a state change, not travel"
        }

        enum Selection {
            static let curve: Swift.String = "easeOut"
            static let duration: CoreGraphics.CGFloat = 0.09
            static let reduceMotion: Swift.String = "unchanged"
        }

        enum SnoozeConfirmHold {
            static let curve: Swift.String = "linear"
            static let duration: CoreGraphics.CGFloat = 4
            static let pauseOnHover: Swift.Bool = true
            static let reduceMotion: Swift.String = "unchanged"
        }

        enum ViewChange {
            static let curve: Swift.String = "easeInOut"
            static let duration: CoreGraphics.CGFloat = 0.16
            static let reduceMotion: Swift.String = "instant swap, 0.10 opacity fade only"
        }
    }

    enum Opacity {
        static let blockDoneFillBlend: CoreGraphics.CGFloat = 0.55
        static let blockDragging: CoreGraphics.CGFloat = 0.85
        static let blockDragOrigin: CoreGraphics.CGFloat = 0.25
        static let blockPastContent: CoreGraphics.CGFloat = 0.55
        static let blockPastFillBlend: CoreGraphics.CGFloat = 0.35
        static let blockPreviewed: CoreGraphics.CGFloat = 0.85
        static let blockSkippedFillBlend: CoreGraphics.CGFloat = 0.65
        static let editorInactiveLayer: CoreGraphics.CGFloat = 0.4
        static let lowEnergyHatchOpacity: CoreGraphics.CGFloat = 1
        static let routineBorder: CoreGraphics.CGFloat = 0.4
    }

    enum Radius {
        static let allDayPill: CoreGraphics.CGFloat = 4
        static let block: CoreGraphics.CGFloat = 5
        static let blockCompact: CoreGraphics.CGFloat = 3
        static let card: CoreGraphics.CGFloat = 8
        static let chip: CoreGraphics.CGFloat = 3
        static let popover: CoreGraphics.CGFloat = 10
        static let sheet: CoreGraphics.CGFloat = 12
        static let travelBand: CoreGraphics.CGFloat = 4
    }

    enum Size {
        static let allDayLabelWidth: CoreGraphics.CGFloat = 52
        static let allDayMaxRows: Swift.Int = 3
        static let allDayRowGap: CoreGraphics.CGFloat = 2
        static let allDayRowHeight: CoreGraphics.CGFloat = 20
        static let blockCascadeIndentMax: CoreGraphics.CGFloat = 22
        static let blockCascadeIndentRatio: CoreGraphics.CGFloat = 0.19
        static let blockCascadeMaxSteps: Swift.Int = 3
        static let blockCascadeMaxVisible: Swift.Int = 5
        static let blockCascadeMinReadableWidth: CoreGraphics.CGFloat = 44
        static let blockColumnGap: CoreGraphics.CGFloat = 2
        static let blockGlyphGap: CoreGraphics.CGFloat = 4
        static let blockGlyphSize: CoreGraphics.CGFloat = 11
        static let blockHitExtension: CoreGraphics.CGFloat = 6
        static let blockMinRenderedHeight: CoreGraphics.CGFloat = 11
        static let blockPadding: CoreGraphics.CGFloat = 5
        static let blockRailWidth: CoreGraphics.CGFloat = 3
        static let blockResizeHandleHeight: CoreGraphics.CGFloat = 6
        static let blockVerticalGap: CoreGraphics.CGFloat = 2
        static let borderEmphasis: CoreGraphics.CGFloat = 1.5
        static let borderRegular: CoreGraphics.CGFloat = 1
        static let borderSelected: CoreGraphics.CGFloat = 2
        static let canvasWidthMin: CoreGraphics.CGFloat = 598
        static let conflictBadgeSize: CoreGraphics.CGFloat = 11
        static let conflictOptionGap: CoreGraphics.CGFloat = 6
        static let conflictOptionRowMinHeight: CoreGraphics.CGFloat = 56
        static let dayColumnCascadeThreshold: CoreGraphics.CGFloat = 72
        static let dayColumnMin: CoreGraphics.CGFloat = 78
        static let dayHeaderHeight: CoreGraphics.CGFloat = 44
        static let editorInspectorWidth: CoreGraphics.CGFloat = 260
        static let editorModeBarHeight: CoreGraphics.CGFloat = 32
        static let hairline: CoreGraphics.CGFloat = 1
        static let hourHeightDay: CoreGraphics.CGFloat = 60
        static let hourHeightWeek: CoreGraphics.CGFloat = 44
        static let inactiveDayNoteMaxWidth: CoreGraphics.CGFloat = 76
        static let inspectorWidthDefault: CoreGraphics.CGFloat = 320
        static let inspectorWidthMax: CoreGraphics.CGFloat = 420
        static let inspectorWidthMin: CoreGraphics.CGFloat = 280
        static let monthCellMaxVisibleRows: Swift.Int = 4
        static let monthCellMinHeight: CoreGraphics.CGFloat = 92
        static let monthCellMinHeightFloor: CoreGraphics.CGFloat = 88
        static let monthCellRowHeight: CoreGraphics.CGFloat = 17
        static let monthWeekdayHeaderHeight: CoreGraphics.CGFloat = 24
        static let nowDotDiameter: CoreGraphics.CGFloat = 7
        static let nowLineThickness: CoreGraphics.CGFloat = 2
        static let popoverActionRowHeight: CoreGraphics.CGFloat = 28
        static let popoverMaxRestRows: Swift.Int = 6
        static let popoverNextBlockMinHeight: CoreGraphics.CGFloat = 84
        static let popoverRestRowHeight: CoreGraphics.CGFloat = 26
        static let popoverWidth: CoreGraphics.CGFloat = 300
        static let previewCanvasBorder: CoreGraphics.CGFloat = 2
        static let resyncPopoverWidth: CoreGraphics.CGFloat = 260
        static let routineEditorColumnMin: CoreGraphics.CGFloat = 84
        static let routineEditorMinHeight: CoreGraphics.CGFloat = 620
        static let routineEditorMinWidth: CoreGraphics.CGFloat = 780
        static let sidebarWidthDefault: CoreGraphics.CGFloat = 232
        static let sidebarWidthMax: CoreGraphics.CGFloat = 320
        static let sidebarWidthMin: CoreGraphics.CGFloat = 180
        static let statusItemGlyphSize: CoreGraphics.CGFloat = 11
        static let statusItemMaxWidth: CoreGraphics.CGFloat = 180
        static let statusItemTitleMinWidth: CoreGraphics.CGFloat = 32
        static let timeGutterWidth: CoreGraphics.CGFloat = 52
        static let toolbarHeight: CoreGraphics.CGFloat = 52
        static let travelBandHeight: CoreGraphics.CGFloat = 18
        static let weekdayToggleSize: CoreGraphics.CGFloat = 24
        static let windowMinHeight: CoreGraphics.CGFloat = 640
        static let windowMinWidth: CoreGraphics.CGFloat = 800
    }

    enum Spacing {
        static let huge: CoreGraphics.CGFloat = 32
        static let lg: CoreGraphics.CGFloat = 12
        static let md: CoreGraphics.CGFloat = 8
        static let sm: CoreGraphics.CGFloat = 6
        static let xl: CoreGraphics.CGFloat = 16
        static let xs: CoreGraphics.CGFloat = 4
        static let xxl: CoreGraphics.CGFloat = 20
        static let xxs: CoreGraphics.CGFloat = 2
        static let xxxl: CoreGraphics.CGFloat = 24
    }

    enum Typography {
        enum AllDayLabel {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "medium"
        }

        enum BlockMeta {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "regular"
        }

        enum BlockTitle {
            static let lineLimit: Swift.Int = 2
            static let size: CoreGraphics.CGFloat = 12
            static let textStyle: Swift.String = "callout"
            static let weight: Swift.String = "semibold"
        }

        enum BlockTitleCompact {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "semibold"
        }

        enum ConflictOptionDelta {
            static let lineLimit: Swift.Int = 2
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "regular"
        }

        enum ConflictOptionTitle {
            static let lineLimit: Swift.Int = 2
            static let size: CoreGraphics.CGFloat = 13
            static let textStyle: Swift.String = "body"
            static let weight: Swift.String = "semibold"
        }

        enum CountdownChip {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 10
            static let textStyle: Swift.String = "caption1"
            static let weight: Swift.String = "semibold"
        }

        enum DayHeaderDate {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 15
            static let textStyle: Swift.String = "title3"
            static let weight: Swift.String = "medium"
        }

        enum DayHeaderWeekday {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textCase: Swift.String = "uppercase"
            static let textStyle: Swift.String = "subheadline"
            static let tracking: CoreGraphics.CGFloat = 0.4
            static let weight: Swift.String = "medium"
        }

        enum EditorModeLabel {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "medium"
        }

        enum HourLabel {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 10
            static let textStyle: Swift.String = "caption1"
            static let weight: Swift.String = "regular"
        }

        enum InactiveDayLabel {
            static let lineLimit: Swift.Int = 2
            static let size: CoreGraphics.CGFloat = 10
            static let textStyle: Swift.String = "caption1"
            static let weight: Swift.String = "medium"
        }

        enum InspectorLabel {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "regular"
        }

        enum InspectorTitle {
            static let lineLimit: Swift.Int = 3
            static let size: CoreGraphics.CGFloat = 15
            static let textStyle: Swift.String = "title3"
            static let weight: Swift.String = "semibold"
        }

        enum InspectorValue {
            static let lineLimit: Swift.Int = 0
            static let size: CoreGraphics.CGFloat = 13
            static let textStyle: Swift.String = "body"
            static let weight: Swift.String = "regular"
        }

        enum MonthDate {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 11
            static let textStyle: Swift.String = "subheadline"
            static let weight: Swift.String = "medium"
        }

        enum PopoverNextMeta {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 15
            static let textStyle: Swift.String = "title3"
            static let weight: Swift.String = "regular"
        }

        enum PopoverNextTitle {
            static let lineLimit: Swift.Int = 2
            static let size: CoreGraphics.CGFloat = 20
            static let textStyle: Swift.String = "title2"
            static let weight: Swift.String = "semibold"
        }

        enum PopoverRefusalRow {
            static let lineLimit: Swift.Int = 0
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 13
            static let textStyle: Swift.String = "body"
            static let weight: Swift.String = "regular"
        }

        enum PopoverRow {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 13
            static let textStyle: Swift.String = "body"
            static let weight: Swift.String = "regular"
        }

        enum PopoverSectionLabel {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textCase: Swift.String = "uppercase"
            static let textStyle: Swift.String = "subheadline"
            static let tracking: CoreGraphics.CGFloat = 0.4
            static let weight: Swift.String = "semibold"
        }

        enum SidebarItem {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 13
            static let textStyle: Swift.String = "body"
            static let weight: Swift.String = "regular"
        }

        enum SidebarSection {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 11
            static let textCase: Swift.String = "uppercase"
            static let textStyle: Swift.String = "subheadline"
            static let tracking: CoreGraphics.CGFloat = 0.4
            static let weight: Swift.String = "semibold"
        }

        enum StatusItem {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 13
            static let textStyle: Swift.String = "body"
            static let weight: Swift.String = "medium"
        }

        enum ToolbarTitle {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 15
            static let textStyle: Swift.String = "title3"
            static let weight: Swift.String = "semibold"
        }

        enum TravelLabel {
            static let lineLimit: Swift.Int = 1
            static let monospacedDigit: Swift.Bool = true
            static let size: CoreGraphics.CGFloat = 10
            static let textStyle: Swift.String = "caption1"
            static let weight: Swift.String = "medium"
        }

        enum WindowLabel {
            static let lineLimit: Swift.Int = 1
            static let size: CoreGraphics.CGFloat = 10
            static let textStyle: Swift.String = "caption1"
            static let weight: Swift.String = "medium"
        }
    }
}


// MARK: - Support

/// Runtime helpers for the generated constants above. Also generated —
/// edit Scripts/generate-tokens.swift, not this file.
enum TokenSupport {

    /// Colour components as they appear in the source hex string (0–255),
    /// kept integral so the emitted values are exact.
    struct RGBA: Sendable, Hashable {
        let red: Int
        let green: Int
        let blue: Int
        let alpha: Int

        var swiftUIColor: SwiftUI.Color {
            SwiftUI.Color(
                .sRGB,
                red: Double(red) / 255.0,
                green: Double(green) / 255.0,
                blue: Double(blue) / 255.0,
                opacity: Double(alpha) / 255.0
            )
        }
    }

    /// A colour that is the same in both appearances.
    static func color(_ rgba: RGBA) -> SwiftUI.Color {
        rgba.swiftUIColor
    }

    /// A colour that resolves against the current appearance. Built as an
    /// AppKit dynamic colour so it also updates correctly inside AppKit-backed
    /// surfaces (the menu bar extra, NSHostingView) and not just in SwiftUI.
    static func color(light: RGBA, dark: RGBA) -> SwiftUI.Color {
        #if canImport(AppKit)
        return SwiftUI.Color(nsColor: DynamicColorCache.shared.color(light: light, dark: dark))
        #else
        return light.swiftUIColor
        #endif
    }
}

#if canImport(AppKit)
/// Dynamic colours are cached by their light/dark pair, and the cache is
/// load-bearing rather than an optimisation.
///
/// `NSColor(name:dynamicProvider:)` returns a brand-new catalog colour on
/// every call, and two such colours are never equal — so without this cache
/// two reads of the *same* token compare unequal. That silently breaks
/// `Equatable` on any type holding a `Color` (Kadence's `BlockStyle`, for one)
/// and makes SwiftUI treat every render as a change.
private final class DynamicColorCache: @unchecked Sendable {
    static let shared = DynamicColorCache()

    private struct Pair: Hashable {
        let light: TokenSupport.RGBA
        let dark: TokenSupport.RGBA
    }

    private let lock = NSLock()
    private var storage: [Pair: NSColor] = [:]

    func color(light: TokenSupport.RGBA, dark: TokenSupport.RGBA) -> NSColor {
        let key = Pair(light: light, dark: dark)
        lock.lock()
        defer { lock.unlock() }
        if let existing = storage[key] { return existing }
        let created = NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
            let resolved = isDark ? dark : light
            return NSColor(
                srgbRed: CGFloat(resolved.red) / 255.0,
                green: CGFloat(resolved.green) / 255.0,
                blue: CGFloat(resolved.blue) / 255.0,
                alpha: CGFloat(resolved.alpha) / 255.0
            )
        }
        storage[key] = created
        return created
    }
}
#endif
